# Generated by Django 3.2.6 on 2021-08-18 10:56

import cryptofolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', cryptofolio.models.CustomDateTimeField(auto_now_add=True)),
                ('usdt_balance', models.FloatField()),
                ('aud_balance', models.FloatField()),
                ('btc_balance', models.FloatField()),
            ],
        ),
    ]
