# Generated by Django 3.2.6 on 2021-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=64)),
                ('api_secret', models.CharField(max_length=64)),
            ],
        ),
    ]
